export const menuCategoriesCollection = [
  {_id:0,_category:'soups'},
  {_id:1,_category:'salats'},
  {_id:2,_category:'main dishes'},
  {_id:3,_category:'deserts'},
  {_id:4,_category:'cold drinks'},
  {_id:5,_category:'hot drinks'},
  {_id:6,_category:'alcohol'},
]

export const menuItemsCollection = [
  {
    _id:0,
    _category: 'soups',
    _items:[
      {
      _id:0,
      _category:'soups',
      _name: 'soup 1',
      _amount:2, _price: 10,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:1,
      _category:'soups',
      _name: 'soup 2',
      _amount:1,
      _price: 15,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:2,
      _category:'soups',
      _name: 'soup 3',
      _amount:1,
      _price: 20,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },]

  },
  {
    _id:1,
    _category: 'salats',
    _items:[
      {
      _id:0,
      _category:'salats',
      _name: 'salat 1',
      _amount:1,
      _price: 10,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:1,
      _category:'salats',
      _name: 'salat 2',
      _amount:1,
      _price: 15,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:2,
      _category:'salats',
      _name: 'salat 3',
      _amount:1,
      _price: 20,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
  ]
  },
  {
    _id:2,
    _category: 'main dishes',
    _items:[
      {
      _id:0,
      _category:'main dishes',
      _name: 'dish 1',
      _amount:1,
      _price: 10,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:1,
      _category:'main dishes',
      _name: 'dish 2',
      _amount:1,
      _price: 15,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:2,
      _category:'main dishes',
      _name: 'dish 3',
      _amount:1,
      _price: 20,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },]

  },
  {
    _id:3,
    _category: 'deserts',
    _items:[
      {
      _id:0,
      _category:'deserts',
      _name: 'desert 1',
      _amount:1,
      _price: 10,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:1,
      _category:'deserts',
      _name: 'desert 2',
      _amount:1,
      _price: 15,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:2,
      _category:'deserts',
      _name: 'desert 3',
      _amount:1,
      _price: 20,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },]

  },
  {
    _id:4,
    _category: 'cold drinks',
    _items:[
      {
      _id:0,
      _category:'cold drinks',
      _name: 'drink 1',
      _amount:1,
      _price: 10,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:1,
      _category:'cold drinks',
      _name: 'drink 2',
      _amount:1,
      _price: 15,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:2,
      _category:'cold drinks',
      _name: 'drink 3',
      _amount:1,
      _price: 20,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },]

  },
  {
    _id:5,
    _category: 'hot drinks',
    _items:[
      {
      _id:0,
      _category:'hot drinks',
      _name: 'hot  1',
      _amount:1,
      _price: 10,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:1,
      _category:'hot drinks',
      _name: 'hot  2',
      _amount:1,
      _price: 15,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:2,
      _category:'hot drinks',
      _name: 'hot  3',
      _amount:1,
      _price: 20,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },]

  },
  {
    _id:6,
    _category: 'alcohol',
    _items:[
      {
      _id:0,
      _category:'alcohol',
      _name: 'alcohol 1',
      _amount:1,
      _price: 10,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:1,
      _category:'alcohol',
      _name: 'alcohol 2',
      _amount:1,
      _price: 15,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },
    {
      _id:2,
      _category:'alcohol',
      _name: 'alcohol 3',
      _amount:1,
      _price: 20,
      _currency: 'eur',
      _takeAway: false,
      _delivery: false, 
      _has_been_sent: false,
      _isAvailable:true,
      _comment:'',
    },]

  }  
]

